let minutes = document.querySelector("#minute");
let seconds = document.querySelector("#second");
let hours = document.querySelector("#hour");
let start = document.querySelector("#start");
let reset = document.querySelector("#reset");
let second= 0;
let minute = 0;
let hour = 0;
let setTime ="thayub"
